services:
  db:
    image: pgvector/pgvector:pg18-trixie
    container_name: deploy-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - deploy-db:/var/lib/postgresql
    networks:
      - deploy-db-network

  caddy:
    image: caddy:latest
    container_name: deploy-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - AGENT_WS_ADDR=${AGENT_WS_ADDR}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:
  deploy-db:

networks:
  web:
    name: web
    driver: bridge

  deploy-db-network:
    name: deploy-db-network
    driver: bridge
