{
    "name": "Deploy",
    "summary": "Module for deploying Odoo on a server.",
    "version": "19.0.0.0.1",
    "author": "Solvti Sp. z o.o.",
    "license": "LGPL-3",
    "category": "Tools",
    "data": [
        "security/ir.model.access.csv",
        "data/github_app_config.xml",
        "views/deploy_menu_items.xml",
        "views/deploy_agent_views.xml",
        "views/deploy_event_views.xml",
        "views/github_app_config_views.xml",
        "views/deploy_module_wizard_views.xml",
        "views/deploy_environment_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "deploy/static/lib/xterm/xterm.css",
            "deploy/static/lib/xterm/xterm.js",
            "deploy/static/src/scss/deploy_style.scss",
            "deploy/static/src/deploy_dashboard/agent_form_controller.js",
            "deploy/static/src/deploy_dashboard/environment_form_controller.js",
            "deploy/static/src/deploy_dashboard/github_cache_service.js",
            "deploy/static/src/deploy_dashboard/environment_history_widget.js",
            "deploy/static/src/deploy_dashboard/environment_logs_widget.js",
            "deploy/static/src/deploy_dashboard/environment_shell_widget.js",
            "deploy/static/src/deploy_dashboard/agent_backups_widget.js",
            "deploy/static/src/deploy_dashboard/agent_branches_widget.js",
            "deploy/static/src/deploy_dashboard/widget_templates.xml",
        ],
    },
    "depends": ["obscure_field", "bus"],
    "external_dependencies": {
        "python": ["cryptography", "pydantic", "requests"],
    },
    "installable": True,
    "application": True,
    "reusable": False,
}
