{
    "name": "Deploy",
    "summary": "Module for deploying Odoo on a server.",
    "version": "19.0.0.0.1",
    "author": "Solvti Sp. z o.o.",
    "license": "LGPL-3",
    "category": "Tools",
    "data": [
        "security/ir.model.access.csv",
        "views/deploy_menu_items.xml",
        "views/deploy_agent_views.xml",
        "views/deploy_event_views.xml",
        "views/github_app_config_views.xml",
        "data/github_app_config.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "deploy/static/src/scss/deploy_style.scss",
            "deploy/static/src/deploy_dashboard/deploy_dashboard.js",
            "deploy/static/src/deploy_dashboard/deploy_dashboard.xml",
            "deploy/static/src/deploy_dashboard/env_panel.js",
            "deploy/static/src/deploy_dashboard/env_panel.xml",
            "deploy/static/src/deploy_dashboard/env_content.js",
            "deploy/static/src/deploy_dashboard/env_content.xml",
            "deploy/static/src/deploy_dashboard/history_tab.js",
            "deploy/static/src/deploy_dashboard/history_tab.xml",
            "deploy/static/src/deploy_dashboard/logs_tab.js",
            "deploy/static/src/deploy_dashboard/logs_tab.xml",
            "deploy/static/src/deploy_dashboard/shell_tab.js",
            "deploy/static/src/deploy_dashboard/shell_tab.xml",
            "deploy/static/src/deploy_dashboard/monitor_tab.js",
            "deploy/static/src/deploy_dashboard/monitor_tab.xml",
            "deploy/static/src/deploy_dashboard/settings_tab.js",
            "deploy/static/src/deploy_dashboard/settings_tab.xml",
            "deploy/static/src/deploy_dashboard/git_command_panel.js",
            "deploy/static/src/deploy_dashboard/git_command_panel.xml",
            "deploy/static/src/deploy_dashboard/backups_tab.js",
            "deploy/static/src/deploy_dashboard/backups_tab.xml",
            "deploy/static/src/deploy_dashboard/agent_form_controller.js",
            "deploy/static/src/deploy_dashboard/deploy_dashboard.scss",
        ],
    },
    "depends": ["obscure_field", "bus"],
    "installable": True,
    "application": True,
    "reusable": True,
}
