name: Release Binary

on:
  push:
    branches: [ "odoosh_ui" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      # --- 1. Validate the Native Binary Compilation via Makefile ---
      - name: Set up Go runtime environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Compile Go Agent Binary
        run: |
          cd agent
          make build-agent

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: agent/build/agent
          tag_name: v1.0.0sh

    
